### ISSUE TITLE
Add a HoF/thanks page

### ISSUE THREAD

**Issue by jacobian** [18F/bug-bounty#12]
We need a page listen those who've disclosed bugs (this is something platforms provide, but since we're DIYing it we need to replicate it)
- [ ] add "how would you like to be credited" fields to issue submissions
- [ ] add HoF page (static is probably easiest? or pull from "fixed" issues?) 

e.g.: https://bounty.github.com/bounty-hunters.html

**Comment by ravip22488** [comment]
Hello

When program expected to begin ?

**Comment by jacobian** [comment]
@ravip22488 we don't have an ETA yet, sorry! When the program launches, we'll announce it on [our blog](https://18f.gsa.gov/blog/); I suggest you follow along there for updates. Thanks!
