### ISSUE TITLE
Create an onboarding checklist

### ISSUE THREAD

**Issue by jacobian** [18F/bug-bounty#26]
We need an onboarding checklist that outlines the steps to follow as we bring new programs into the bounty. It should cover the various steps we take between accepting a program and launching the bounty.

Ideally, we'd develop this before our first program. Practically, it may be easiest to just muddle through the first one and take notes (which we can do here in this issue) and let the first program be our canary.

**Comment by afeld** [comment]
[The pre-joining steps](https://github.com/18F/bug-bounty/blob/master/project-instructions.md)

**Comment by afeld** [comment]
Closing as stale.
