### ISSUE TITLE
Use CVSS terminilogy where necessary.

### ISSUE THREAD

**Issue by EdOverflow** [18F/bug-bounty#30]
> **Validation:** As issues are reported, you'll need to review the reports to validate them. HackerOne will be performing initial triage to reproduce the issue and assign a severity. <sup>[[1]](https://github.com/18F/bug-bounty/blob/master/project-instructions.md)</sup>

The CVSS score calculator on HackerOne only includes the _CVSS v3.0 Base Score_ metric <sup>[[2]](https://www.first.org/cvss/specification-document#2-Base-Metrics)</sup>. This is purely the technical severity; therefore, I would suggest either rephrasing that paragraph and mentioning the CVSS metric, or using the term "priority" as you did later on in the document:

> Validation is complete when you have enough information from the reporter to implement a fix and assign it a **priority**, or enough information to dismiss it as not a bug.

**Comment by its-a-lisa-at-work** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
