### ISSUE TITLE
HackerOne SAML/SSO

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/bug-bounty#37]
## Background information

Need to enable SAML/SSO with HackerOne to be compliant with FedRAMP. 

## Acceptance criteria

- [x] HackerOne has SSO or SAML set up

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
From Sitora:

> GSA just configured SAML for the @gsa.gov domain, which applies across programs
