### ISSUE TITLE
Design nice-to-haves

### ISSUE THREAD

**Issue by jacobian** [18F/bug-bounty#9]
The design right now is sparten, but OK. This is a grab-bag of nice-to-have design stuff that I hope to implement (or get help with), but if it doesn't happen that's OK.
- [ ] nav (top or side) to the various sections and pages
- [ ] a nicer-looking submission form (fill the whole width, better help text)
- [ ] have the form show extended help text for targets and types, a la HackerOne's submission forms
- [ ] a picture or drawing on the landing page, just so it's not so starkly white

**Comment by konklone** [comment]
Grabbing stuff from the pages.18f.gov template and/or the [draft US Web Design Standards](https://standards.usa.gov/) would at least move it from spartan to presentable.

**Comment by brendansudol** [comment]
happy to help you with this next week :)
